USE specialweek;

-- Image (Réel vs IA) (type_question = 3)

INSERT INTO Jeu_quizz (type_question, media_url, option_a, option_b, option_c, option_d, reponse_correcte, explication, points_accordes) VALUES
(3, '/assets/img/quizz/reel/photo_ete_7.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Cette image d''une personne âgée assise sur un banc avec des pigeons est une vraie photo prise par un photographe.', 10),
(3, '/assets/img/quizz/AI/image_35.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Cette image de Taylor Swift coiffée d''une couronne d''or futuriste avec des vêtements de science-fiction a été générée par une IA.', 10),
(3, '/assets/img/quizz/AI/image_36.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un pape vêtu d''une doudoune Balenciaga rose – cette image surréaliste est un deepfake généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_176.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une promenade dans une rue parisienne avec la Tour Eiffel en arrière-plan : une vraie photographie touristique.', 10),
(3, '/assets/img/quizz/AI/image_37.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un chien ayant huit pattes en train de voler dans le ciel avec des ailes arc-en-ciel est clairement une création IA.', 10),
(3, '/assets/img/quizz/AI/image_38.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main avec 8 doigts qui sort d''une tasse de café – un indice classique d''une image générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_85.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant jouant au foot dans un parc local : une simple photo de vie quotidienne.', 10),
(3, '/assets/img/quizz/AI/image_39.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une chaise en train de flotter au-dessus d''une tasse de café défiant la gravité – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_267.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un coucher de soleil sur une plage avec des vagues : une photographie naturelle.', 10),
(3, '/assets/img/quizz/AI/image_40.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet bizarre dans les vitres avec des contours flous et incompréhensibles – signe d''une génération IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_249.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une personne tenant un livre dans une bibliothèque : une scène réaliste photographiée.', 10),
(3, '/assets/img/quizz/AI/image_41.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Quatre doigts sur une main au lieu de cinq – erreur courante des générateurs IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_266.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un groupe d''amis rigolant autour d''une table de restaurant : une vraie photo de moment partagé.', 10),
(3, '/assets/img/quizz/AI/image_42.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une texture de peau bizarrement lisse ou pixelisée avec des zones floues unexpliquées – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_159.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un paysage montagneux avec des arbres et un lac : une belle photographie naturelle.', 10),
(3, '/assets/img/quizz/AI/image_43.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un texte illisible ou des caractères incompréhensibles sur un panneau – les IA luttent avec le texte.', 10),
(3, '/assets/img/quizz/reel/photo_ete_30.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une chat endormi sur un canapé : une photo domestique ordinaire.', 10),
(3, '/assets/img/quizz/AI/image_44.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une biologie absurde : un oiseau avec des dents ou des yeux asymétriques – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_260.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un repas servi dans une assiette : une photographie culinaire normale.', 10),
(3, '/assets/img/quizz/AI/image_46.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une femme portant des vêtements qui changent de texture comme de la lave liquide autour de son corps – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_70.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un jeune homme dans un magasin achetant un café : une photographie quotidienne classique.', 10),
(3, '/assets/img/quizz/AI/image_47.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des bâtiments avec une architecture surréaliste impossibles géométriquement – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_195.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une femme souriant avec sa famille lors d''un repas de famille : une simple photo de réunion.', 10),
(3, '/assets/img/quizz/AI/image_48.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main humaine se transformant en patte d''animal – impossible réellement, générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_243.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un marché avec des étals de fruits et légumes : une vraie photographie de commerce.', 10),
(3, '/assets/img/quizz/AI/image_49.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des bijoux qui brillent avec des reflets étrangement pixelisés – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_26.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant dormant dans son lit la nuit : une photo sentimentale normale.', 10),
(3, '/assets/img/quizz/AI/image_50.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne ayant 11 doigts sur chaque main – erreur classique des générateurs IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_22.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Deux chats jouant ensemble sur un tapis : une photo animalière authentique.', 10),
(3, '/assets/img/quizz/AI/image_51.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un robot qui fond physiquement comme du métal liquide – une création IA surréaliste.', 10),
(3, '/assets/img/quizz/reel/photo_ete_136.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un bureau avec ordinateur et documents : un espace de travail photographié.', 10),
(3, '/assets/img/quizz/AI/image_52.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des yeux qui n''ont pas la même forme ou taille sur le même visage – glitch de l''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_123.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un paysage forestier avec des arbres, mousse et rochers : une naturelle photographie.', 10),
(3, '/assets/img/quizz/AI/image_53.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet qui existe en plusieurs copies avec des deformations bizarres – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_46.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une fille lisant un livre dans une bibliothèque : une scène de lecture réaliste.', 10),
(3, '/assets/img/quizz/AI/image_54.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet qui ne suit pas les lois physiques de la réflexion – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_109.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une plage avec des vagues et du sable : une photographie de vacances.', 10),
(3, '/assets/img/quizz/AI/image_55.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des lettres qui changent légèrement dans la même image – les IA n''arrivent pas bien avec le texte.', 10),
(3, '/assets/img/quizz/AI/image_1.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une femme avec une moitié du corps faite de cristal et l''autre de chair – impossible réellement, créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_265.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant jouant avec un ballon dans un jardin : une scène enfantine normale.', 10),
(3, '/assets/img/quizz/AI/image_2.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des cheveux qui changent de couleur et de texture dans une même image – glitch IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_137.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un homme travaillant à son bureau avec un ordinateur : une photo de travail classique.', 10),
(3, '/assets/img/quizz/AI/image_3.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment qui ça penche d''un côté de manière surréaliste – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_89.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un groupe de gens partageant un repas : une vraie scène de convivialité.', 10),
(3, '/assets/img/quizz/AI/image_4.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des dents qui sortent de manière incohérente du visage – erreur IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_214.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une fleur avec ses détails naturels : une photographie botanique.', 10),
(3, '/assets/img/quizz/AI/image_5.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des yeux avec des pupilles de tailles différentes – signe de génération IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_209.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un coucher de soleil sur l''océan : une vraie photographie naturelle.', 10),
(3, '/assets/img/quizz/AI/image_6.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main avec des doigts mal proportionnés et des articulations bizarres – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_210.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un chien courant dans un parc : une photo animalière authentique.', 10),
(3, '/assets/img/quizz/AI/image_7.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet qui flotte mystérieusement sans support visible défiant la gravité – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_232.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un portrait d''une personne souriante : une vraie photographie.', 10),
(3, '/assets/img/quizz/AI/image_8.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une texture de tissu qui change bizarrement de motif – glitch IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_274.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une rue animée avec voitures et piétons : une vraie photo urbaine.', 10),
(3, '/assets/img/quizz/AI/image_9.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet de miroir qui ne correspond pas à l''objet – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_157.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Des fleurs dans un vase : une nature morte photographiée.', 10),
(3, '/assets/img/quizz/AI/image_10.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'De l''eau qui coule dans des directions incohérentes – générée par IA.', 10),
(3, '/assets/img/quizz/AI/image_11.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un élephant translucide avec des ailes de papillon – clairement généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_92.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une fille tenant un parapluie sous la pluie : une vraie photo d''un jour pluvieux.', 10),
(3, '/assets/img/quizz/AI/image_12.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des bâtiments avec des portes et fenêtres qui ne correspondent pas – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_242.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un repas cuisinésprésenté sur une table : une photo culinaire réelle.', 10),
(3, '/assets/img/quizz/AI/image_13.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne avec des oreilles en positions bizarres ou asymétriques – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_73.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Des enfants jouant dans un parc : une vraie scène de loisir.', 10),
(3, '/assets/img/quizz/AI/image_14.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une chaise avec quatre jambes d''une même longueur impossible – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_277.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un coucher de soleil coloré : une magnifique photographie naturelle.', 10),
(3, '/assets/img/quizz/AI/image_15.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des lettres qui changent de police ou de taille de manière incohérente – IA signe.', 10),
(3, '/assets/img/quizz/reel/photo_ete_43.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un cafè avec des clients : une vraie photo du quotidien.', 10),
(3, '/assets/img/quizz/AI/image_16.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des mains avec des doigts qui se chevauchent bizarrement – erreur classique IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_237.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un paysage urbain avec rues et buildings : une vraie photo de ville.', 10),
(3, '/assets/img/quizz/AI/image_17.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne qui semble fondre physiquement à la limite de l''image – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_110.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un animal dans son habitat naturel : une photo de faune authentique.', 10),
(3, '/assets/img/quizz/AI/image_18.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet dans l''eau qui ne correspond pas à la position de l''objet – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_71.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une forêt avec arbres, feuilles et lumière naturelle : une vraie photographie.', 10),
(3, '/assets/img/quizz/AI/image_19.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des motifs ou textures qui semblent impossibles géométriquement – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_105.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un vélo dans une rue : une photo de transport vélos ordinaire.', 10),
(3, '/assets/img/quizz/AI/image_20.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un ciel avec des nuages de formes impossibles – créé par IA.', 10),
(3, '/assets/img/quizz/AI/image_21.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une fusée qui traverse un nuage en déformant l''air de manière impossible – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_134.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant dessinant sur le sol avec une craie : une vraie photo de jeu.', 10),
(3, '/assets/img/quizz/AI/image_22.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main qui s''étiré vers l''infini de manière surréaliste – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_84.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une piscine avec reflets d''eau naturels : une vraie photo de loisir.', 10),
(3, '/assets/img/quizz/AI/image_23.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet qui existe dans plusieurs états contradictoires – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_4.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un jardin avec fleurs et plantes : une vraie photo botanique.', 10),
(3, '/assets/img/quizz/AI/image_24.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des yeux qui regardent dans deux directions différentes – erreur classique IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_292.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une montagne enneigée au loin : une vraie photographie de paysage.', 10),
(3, '/assets/img/quizz/AI/image_25.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des murs qui se croisent de manière géométriquement impossible – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_291.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une personne faisant du skateboard dans un parc : une vraie photo de sport.', 10),
(3, '/assets/img/quizz/AI/image_26.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une couleur qui transition bizarrement sans dégradé progressif – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_217.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une famille au cinéma regardant un film : une vraie photo de loisir.', 10),
(3, '/assets/img/quizz/AI/image_27.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un visage avec une expression anatomiquement impossible – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_246.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un chat dormant paisiblement : une vraie photo animale.', 10),
(3, '/assets/img/quizz/AI/image_28.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une texture de cuir qui semble vivante ou mouvante – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_93.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un marché nocturne avec lumières artificielles : une vraie photo urbaine.', 10),
(3, '/assets/img/quizz/AI/image_29.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un ciel avec des constellations qui ne correspondent à aucune réalité – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_23.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un apiculteur travaillant avec des ruches : une vraie photo de travail.', 10),
(3, '/assets/img/quizz/AI/image_30.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des fleurs qui poussent en spirale impossible – générée par IA.', 10),
(3, '/assets/img/quizz/AI/image_61.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un piano qui coule dans l''eau comme du miel – physiquement impossible, créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_65.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant portant un sac à dos dans une cour d''école : une vraie photo d''école.', 10),
(3, '/assets/img/quizz/AI/image_62.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des fleurs avec des pétales en nombre impossible (7 fois l''infini) – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_229.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un fermier travaillant dans un champ : une vraie photo de travail agricole.', 10),
(3, '/assets/img/quizz/AI/image_63.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet dans un verre qui révèle quelque chose d''impossible – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_175.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Des gens marchant dans une rue commerciale : une vraie photo urbaine.', 10),
(3, '/assets/img/quizz/AI/image_64.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une chaise avec des proportions géométriquement bizarres – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_151.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un chien avec ses propriétaires devant une maison : une vraie photo familiale.', 10),
(3, '/assets/img/quizz/AI/image_65.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des yeux avec reflets qui ne correspondent pas à l''angle de lumière – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_104.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un marché de fruits et légumes : une vraie photo commerciale.', 10),
(3, '/assets/img/quizz/AI/image_66.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des cheveux qui semblent partiellement transparents ou flous de manière anormale – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_251.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un athlète courante une course : une vraie photo de sport.', 10),
(3, '/assets/img/quizz/AI/image_67.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main qui sort d''un objet il ne devrait pas être possible – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_257.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un groupe de personnes partage un gâteau : une vraie photo de convivialité.', 10),
(3, '/assets/img/quizz/AI/image_68.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un paysage avec une montagne et un soleil qui semble en deux endroits – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_220.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une personne utilisant un ordinateur dans un bureau : une vraie photo d''informatique.', 10),
(3, '/assets/img/quizz/AI/image_69.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des doigts qui semblent fusionner ou se chevaucher bizarrement – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_205.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Des étudiants dans une salle de classe : une vraie photo d''école.', 10),
(3, '/assets/img/quizz/AI/image_70.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment avec des fenêtres dans des positions illogiques – générée par IA.', 10),
(3, '/assets/img/quizz/AI/image_71.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un train transparent où on voit à travers les wagon – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_102.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une personne tenant un microphone dans un studio : une vraie photo audio.', 10),
(3, '/assets/img/quizz/AI/image_72.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des vêtements qui semblent flotter sans corps dessous – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_135.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un restaurant avec serveur et clients : une vraie photo de commerce.', 10),
(3, '/assets/img/quizz/AI/image_73.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un animal avec des caractéristiques d''une autre espèce – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_290.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un parc avec enfants jouants : une vraie photo de loisir.', 10),
(3, '/assets/img/quizz/AI/image_74.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des mains qui apparaissent et disparaissent dans l''image – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_148.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Una voiture garée devant une maison : une vraie photo résidentielle.', 10),
(3, '/assets/img/quizz/AI/image_75.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des objets qui flottent sans support visible – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_236.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un musicien jouant d''un instrument : une vraie photo artistique.', 10),
(3, '/assets/img/quizz/AI/image_76.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un texte illisible ou avec caractères bizarres – erreur typique IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_280.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un étudiant étudiant dans une bibliothèque : une vraie photo éducative.', 10),
(3, '/assets/img/quizz/AI/image_77.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne avec quatre bras visible – clairement créée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_91.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un pique-nique en famille dans un parc : une vraie photo social.', 10),
(3, '/assets/img/quizz/AI/image_78.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des ombres qui n''ont aucun sens par rapport à la lumière – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_107.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une personne faisant du yoga sur un tapis : une vraie photo de wellness.', 10),
(3, '/assets/img/quizz/AI/image_79.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une géométrie d''espace qui est impossible physiquement – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_49.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un mariage avec mariée et marié : une vraie photo d''événement.', 10),
(3, '/assets/img/quizz/AI/image_80.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un visage avec une moitié qui est dessinée autrement que l''autre – créé par IA.', 10),
(3, '/assets/img/quizz/AI/image_31.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une montagne qui semble fondre dans le ciel – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_178.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Des amis posant pour une photo devant un monument : une vraie photo touristique.', 10),
(3, '/assets/img/quizz/AI/image_32.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne avec des reflets d''yeux qui sont asymétriques – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_263.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un artiste peintant sur une toile : une vraie photo de d''création.', 10),
(3, '/assets/img/quizz/AI/image_33.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des murs qui ne se joignent pas correctement à l''angle – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_52.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un laboratoire scientifique avec équipement​s : une vraie photo de recherches.', 10),
(3, '/assets/img/quizz/AI/image_81.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des fleurs avec nombre de pétales impossible – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_40.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant construisant un château de sable : une vraie photo de plage.', 10),
(3, '/assets/img/quizz/AI/image_82.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une réflexion dans l''eau qui ne suit pas les lois de physique – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_181.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Des ouvriers travaillant sur un chantier : une vraie photo de construction.', 10),
(3, '/assets/img/quizz/AI/image_83.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des animaux avec des caractéristiques mélangées – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_218.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un photographe avec sa caméra : une vraie photo artistique.', 10),
(3, '/assets/img/quizz/AI/image_84.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main qui semble avoir trop ou trop peu de doigts – signe classique d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_173.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Des clients dans un café buvagnes : une vraie photo intérieure.', 10),
(3, '/assets/img/quizz/AI/image_85.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment avec des portes à des endroits géométriquement impossible – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_252.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un parent jouant avec son enfant : une vraie photo familiale.', 10),
(3, '/assets/img/quizz/AI/image_86.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un visage avec une moitié qui change d''expression – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_120.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un professeur écrivant au tableau noir : une vraie photo d''enseignement.', 10),
(3, '/assets/img/quizz/AI/image_87.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des textures qui répétent le même pattern bizarrement – signe d''IA.', 10),
(3, '/assets/img/quizz/AI/image_88.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une cascade qui coule vers le haut – défie la physique, créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_150.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un bibliothécaire organisant les livres : une vraie photo professionnelle.', 10),
(3, '/assets/img/quizz/AI/image_89.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des cheveux qui changent de couleur brutalement sans transition – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_36.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant mangeant un gâteau au anniversaire : une vraie photo festive.', 10),
(3, '/assets/img/quizz/AI/image_90.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet qui semble partiellement dissout – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_282.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un médecin avec stéthoscope en cabinet : une vraie photo médicale.', 10),
(3, '/assets/img/quizz/AI/image_91.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une ombre qui n''a pas de source de lumière – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_14.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un groupe de touristes visitant un musée : une vraie photo culturelle.', 10),
(3, '/assets/img/quizz/AI/image_92.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des doigts avec articulations bizarrement proportionnées – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_56.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un motocycliste sur sa moto : une vraie photo de transport.', 10),
(3, '/assets/img/quizz/AI/image_93.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment qui devient progressivement transparent – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_163.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un couple dansant à un mariage : une vraie photo d''événement.', 10),
(3, '/assets/img/quizz/AI/image_94.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un visage avec une moitié beaucoup plus grande que l''autre – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_261.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un agriculteur récoltant des légumes : une vraie photo rurale.', 10),
(3, '/assets/img/quizz/AI/image_95.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des éléments qui ne respectent pas l''échelle (fourmi grande comme humain) – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_207.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant dormant avec son jouet : une vraie photo intime.', 10),
(3, '/assets/img/quizz/AI/image_96.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un texte qui semble flotter dans l''espace – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_233.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un chef cuisinier dans sa cuisine : une vraie photo professionnelle.', 10),
(3, '/assets/img/quizz/AI/image_97.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des reflets dans les yeux qui semblent incorrects – signe d''IA.', 10),
(3, '/assets/img/quizz/AI/image_98.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un arbre qui change de saison instantanément entre branches – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_168.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un étudiant travaillant dans une bibliothèque : une vraie photo d''étude.', 10),
(3, '/assets/img/quizz/AI/image_99.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un vêtement qui semble fondre dans la peau – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_180.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un groupe d''enfants jouant à l''école : une vraie photo scolaire.', 10),
(3, '/assets/img/quizz/AI/image_100.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne avec six doigts sur une main – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_190.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un festival avec stands et visiteurs : une vraie photo d''événement.', 10),
(3, '/assets/img/quizz/AI/image_101.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des proportions du corps qui semble bizarrement distordue – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_162.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un coucher de soleil sur la plage : une vraie photographie naturelle.', 10),
(3, '/assets/img/quizz/AI/image_102.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main avec pouces asymétriques – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_197.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un restaurant bondé avec clients : une vraie photo commerciale.', 10),
(3, '/assets/img/quizz/AI/image_103.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un insecte avec nombre de pattes incorrects – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_131.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un jardin botanique avec différentes l''étant : une vraie photo.', 10),
(3, '/assets/img/quizz/AI/image_104.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des yeux qui semblent regarder sans coordonner – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_42.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un photographe professionnel avec appareil : une vraie photo.', 10),
(3, '/assets/img/quizz/AI/image_105.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une architecture qui défie les lois physiques – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_115.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un train avec passagers : une vraie photo de transport.', 10),
(3, '/assets/img/quizz/AI/image_106.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet dans un verre qui ne correspond pas à l''objet – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_9.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un salon de coiffure avec clients : une vraie photo de service.', 10),
(3, '/assets/img/quizz/AI/image_107.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des textures de peau anormalement lisse ou pixelisée – créé par IA.', 10),
(3, '/assets/img/quizz/AI/image_108.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment qui fond comme du fromage – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_245.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un jardinier plantant des fleurs : une vraie photo de travail.', 10),
(3, '/assets/img/quizz/AI/image_109.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet avec plusieurs shadows impossibles – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_51.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant ouvrant un cadeau de Noël : une vraie photo festive.', 10),
(3, '/assets/img/quizz/AI/image_110.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un animal hybrid (lion + aigle) – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_122.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un musicien en concert sur scène : une vraie photo live.', 10),
(3, '/assets/img/quizz/AI/image_111.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des murs qui se rencontrent impossiblement – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_44.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un barista préparant un café : une vraie photo commerciale.', 10),
(3, '/assets/img/quizz/AI/image_112.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un visage qui change expression entre gauche/droite – généré par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_67.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un parachutiste descendant dans le ciel : une vraie photo sport.', 10),
(3, '/assets/img/quizz/AI/image_113.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des cheveux dont la texture semble invraisemblable – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_149.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un gymnaste en équilibre : une vraie photo athletic.', 10),
(3, '/assets/img/quizz/AI/image_114.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne partiellement invisible ou transparent – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_258.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un bouquet de fleurs fraîches : une vraie photo florale.', 10),
(3, '/assets/img/quizz/AI/image_115.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des reflets oculaires qui ne match pas positions – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_276.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un couple se mariant : une vraie photo de mariage.', 10),
(3, '/assets/img/quizz/AI/image_116.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment par impossible proportions – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_213.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un camping sous les étoiles : une vraie photo nature.', 10),
(3, '/assets/img/quizz/AI/image_117.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une texture dont le pattern se répète bizarrement – signe d''IA.', 10),
(3, '/assets/img/quizz/AI/image_118.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une personne floue partiellement avec contours indefinits – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_58.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un agent immobilier montrant une maison : une vraie photo commerciale.', 10),
(3, '/assets/img/quizz/AI/image_119.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet qui semble partiellement pixelisé – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_225.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un chargement de marchandises dans un camion : une vraie photo logistique.', 10),
(3, '/assets/img/quizz/AI/image_120.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment avec entrée qui semble mener nulle part – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_118.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une personne en tenue médicale dans un hôpital : une vraie photo.', 10),
(3, '/assets/img/quizz/AI/image_121.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des mains qui semblent se multiplier – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_256.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un match de tennis avec joueurs : une vraie photo sportive.', 10),
(3, '/assets/img/quizz/AI/image_122.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un ciel avec couleurs impossibles ou irréalistes – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_279.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un bureau d''avocats avec gens travaillant : une vraie photo.', 10),
(3, '/assets/img/quizz/AI/image_123.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Asymétrie faciale excessive ou anormale – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_108.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un architecte devant ses plans : une vraie photo professionnelle.', 10),
(3, '/assets/img/quizz/AI/image_124.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet qui semble devenir opaque/transparent progressivement – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_112.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant à la fête d''anniversaire avec gâteau : une vraie photo.', 10),
(3, '/assets/img/quizz/AI/image_125.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des pixels visiblement en défaut sur une partie – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_2.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Une personne se brossant les dents : une vraie photo d''hygiène.', 10),
(3, '/assets/img/quizz/AI/image_126.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une géométrie d''objet qui ne résiste pas à la gravité – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_203.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un élève résolvant une équation au tableau : une vraie photo d''école.', 10),
(3, '/assets/img/quizz/AI/image_127.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des yeux avec reflets qui semblent générés – créé par IA.', 10),
(3, '/assets/img/quizz/AI/image_128.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un humain avec quatre bras visiblement – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_204.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un présentateur TV dans studio : une vraie photo professionnelle.', 10),
(3, '/assets/img/quizz/AI/image_129.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des objets qui flottent dans chaos dans l''air – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_202.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un dentiste examinant un patient : une vraie photo médicale.', 10),
(3, '/assets/img/quizz/AI/image_130.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet correct qui viole lois optiques – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_50.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un groupe de danseurs en scène : une vraie photo performance.', 10),
(3, '/assets/img/quizz/AI/image_131.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une main avec nombre doigts incorrect – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_28.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un programmeur programmant code : une vraie photo travail.', 10),
(3, '/assets/img/quizz/AI/image_132.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Une texture qui semble liquide solidifiée anormalement – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_206.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un équipe médicale opérant : une vraie photo medical.', 10),
(3, '/assets/img/quizz/AI/image_133.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un paysage avec deux sources lumière contradictoires – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_62.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un astronome regardant un télescope : une vraie photo.', 10),
(3, '/assets/img/quizz/AI/image_134.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des proportions de bâtiment anormalement distortionné – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_211.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un cuisinier préparant plat : une vraie photo culinaire.', 10),
(3, '/assets/img/quizz/AI/image_135.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet partiellement visible/invisible – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_80.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un jardinier paysagiste travaillant : une vraie photo.', 10),
(3, '/assets/img/quizz/AI/image_136.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un visage avec une moitié distordu – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_41.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un ingénieur sur chantier : une vraie photo construction.', 10),
(3, '/assets/img/quizz/AI/image_137.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des cheveux avec structure impossible géométriquement – créé par IA.', 10),
(3, '/assets/img/quizz/AI/image_138.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un humain avec oreilles en formes impossibles – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_106.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un mannequin retouching dans atelier : vraie photo fashion.', 10),
(3, '/assets/img/quizz/AI/image_139.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet qui semble melting partiellement – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_284.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un peintre avec son chevalet : vraie photo artist.', 10),
(3, '/assets/img/quizz/AI/image_140.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Proportions faciales extrêmement imbalancées – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_174.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un apiculteur avec ruches : vraie photo agricultural.', 10),
(3, '/assets/img/quizz/AI/image_141.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des doigts qui semblent fusionné – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_294.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un astronome observant ciel : vraie photo science.', 10),
(3, '/assets/img/quizz/AI/image_142.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un reflet qui viole optique physics – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_297.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un coureur marathonien : vraie photo sports.', 10),
(3, '/assets/img/quizz/AI/image_143.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des cheveux avec texture impossible – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_262.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un sculpteur travail marbre : vraie photo artist.', 10),
(3, '/assets/img/quizz/AI/image_144.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un bâtiment qui semble soft/liquide – créé par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_16.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un navigateur maritime : vraie photo profession.', 10),
(3, '/assets/img/quizz/AI/image_145.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Des yeux avec positions anormales – générée par IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_152.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un enfant apprenant lecture : vraie photo education.', 10),
(3, '/assets/img/quizz/AI/image_146.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Un objet multiplicité anormale – signe d''IA.', 10),
(3, '/assets/img/quizz/reel/photo_ete_153.jpg', 'Réel', 'IA', NULL, NULL, TRUE, 'Un bouquiniste antique shop : vraie photo commerce.', 10),
(3, '/assets/img/quizz/AI/image_147.jpg', 'Réel', 'IA', NULL, NULL, FALSE, 'Pixélisation évidente zones aléatoires – créé par IA.', 10);
