USE specialweek;

-- Vrai/Faux (type_question = 2)

INSERT INTO Jeu_quizz (type_question, media_url, option_a, option_b, option_c, option_d, reponse_correcte, explication, points_accordes) VALUES
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les images générées par IA peuvent avoir des défauts : mains bizarres, texte illisible, reflets étranges. Un bon observateur peut les détecter.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'ChatGPT a été entraîné sur des milliards de textes et peut générer du contenu remarquablement réaliste.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes peuvent être utilisés pour créer de fausses vidéos de politiques, de célébrités ou de n''importe qui.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'L''IA est programmée pour être honnête et ne peut jamais générer d''informations fausses volontairement.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les algorithmes des réseaux sociaux nous montrent surtout du contenu qui nous plaît, ce qui crée une "bulle informationnelle".', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet est le moyen le plus fiable pour vérifier une information car tout y est contrôlé.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Une même information peut être présentée différemment selon la source, reflétant un biais ou un parti pris.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les influenceurs doivent légalement indiquer quand ils publicisez un produit qui les rémunère.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les journalistes professionnels ne peuvent jamais se tromper ou publier d''informations inexactes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Checker les sources et croiser les informations sont les meilleures défenses contre la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les deepfakes sont faciles à détecter car la technologie IA n''est pas avancée.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA peut reproduire les biais contenus dans les données sur lesquelles elle a été entraînée.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les fausses informations partagées rapidement sur les réseaux peuvent influencer les opinions publiques.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tout ce qui est publié sur un site officiel est automatiquement vrai et vérifiable.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les générateurs d''images IA comme Dall-E peuvent créer des images que personne n''a jamais vues.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un million de partages d''une information sur les réseaux sociaux la rend automatiquement vraie.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Vérifier une information avant de la partager contribue à réduire la propagation de la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'L''IA est apte à remplacer complètement les fact-checkers et la vérification manuelle.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes sont utilisés malveillantement pour tromper les gens ou les nuire.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les IA peuvent être entraînées sur des données contenant des préjugés, et reproduisent ces biais.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les réseaux sociaux vérifient automatiquement chaque information avant publication.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les informations partagées par des amis peuvent aussi être fausses ou trompeuses.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'L''IA ne peut créer que du texte, pas d''images ou de vidéos.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les générateurs d''images IA comme Dall-E, Midjourney créent du contenu à partir d''un texte.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les bulles informationnelles nous enferment dans nos propres idées et opinions.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un article viral sur les réseaux sociaux est automatiquement vérifié et fiable.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les influenceurs reçoivent souvent de l''argent pour promouvoir un produit sans le dire.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Des deepfakes peuvent être utilisés pour manipuler l''opinion publique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'C''est facile de reconnaître une image générée par IA juste en la regardant.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes représentent un risque pour la sécurité personnelle et l''identité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les titres sensationnalistes peuvent tromper les gens sans lire le contenu complet.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Seules les personnes sans éducation sont victimes de désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA peut être utilisée pour à la fois créer et détecter des deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les médias traditionnels font aussi des erreurs et peuvent diffuser des infos inexactes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les gouvernements contrôlent 100% de ce qu''on voit sur les réseaux sociaux.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La désinformation peut influencer les élections et les décisions politiques.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les mèmes et les images drôles peuvent aussi contenir de fausses informations.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Googler rapidement est la meilleure façon de vérifier une information complexe.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Il est plus facile de partager rapidement une fausse info que de vérifier sa véracité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les algorithmes sont programmés pour favoriser la vérité plutôt que l''engagement.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La désinformation peut influencer les comportements, les opinions et les décisions des gens.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les images générées par IA peuvent être très réalistes et tromper les gens.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Une personne éduquée ne peut jamais être victime de désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les journalistes peuvent faire des erreurs involontaires dans leurs reportages.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les réseaux sociaux facilitent la propagation rapide de fausses informations.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Seuls les réseaux sociaux diffusent de la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes pose un risque pour la sécurité des élections et de la démocratie.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA générative peut crée du texte, des images et des vidéos réalistes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tous les influenceurs divulguent clairement quand ils publicisent un produit payé.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les bulles informationnelles nous isolent des opinions différentes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'On peut être manipulé par une fausse information même si on pense être critique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Si un article a beaucoup de likes, cela garantit qu''il est vrai.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La vérification des sources demande du temps, mais c''est crucial contre la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les mèmes peuvent contenir des informations fausses ou trompeuses.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'L''IA ne peut jamais être utilisée pour combattre la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les données personnelles peuvent être utilisées pour créer des deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Une image officiellement publiée sur un site gouvernemental est nécessairement vraie.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les IA génératives ne peuvent créer que du texte, pas d''images.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Un mensonge dit mille fois peut sembler vrai pour beaucoup de gens.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les cyberattaques utilisent souvent de fausses informations pour distraire.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tous les faux documents créés par IA sont immédiatement détectables.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les réseaux sociaux ont une responsabilité dans la propagation de la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Un fact-checker est quelqu''un qui vérifie les informations avant publication.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les parents n''ont pas besoin d''éduquer leurs enfants sur Internet.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Des études montrent que les mensonges se propagent plus vite que les vérités.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'L''IA générative ChatGPT ne commet jamais d''erreurs factuelles.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''utilisation de sources d''images fiables est importante pour éviter les fausses images.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La liberté d''expression doit être équilibrée avec la responsabilité de dire la vérité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les deepfakes ne peuvent affecter que les personnes publiques.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La désinformation peut causer des dégâts psychologiques et sociaux.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Chercher des sources multiples est une perte de temps.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les utilisateurs doivent apprendre à identifier les publicités déguisées en contenu.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes deviennent techniquement plus difficiles à détecter au fil du temps.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un site avec beaucoup de publicités est toujours une source fiable d''infos.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les IA peuvent être entraînes à détecter et combattre d''autres IA.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les enfants ne sont pas concernés par la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les bots sociaux peuvent automatiquement amplifier certains messages en ligne.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet a rendu la vérification des informations plus facile qu''avant.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Une vidéo peut être manipulée pour montrer quelque chose qui ne s''est jamais produit.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les images de stock ne peuvent jamais être manipulées ou utilisées hors contexte.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les IA peuvent générer des textes académiques convincants mais factuellement faux.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La polarisation des opinions est amplifiée par les bulles informationnelles.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les publicités en ligne sont toujours clairement identifiées comme telles.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Une information partagée par un scientifique peut encore être fausse.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les gouvernements maîtrisent parfaitement la désinformation sur Internet.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les médias sociaux conservent les données utilisateurs qui peuvent être utilisées pour des deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''éducation au numérique dès l''école primaire est bénéfique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Vérifier chaque information prend moins d''une seconde.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les historiens et archéologues doivent adapter leurs méthodes face aux deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'L''authenticité d''une image est facile à garantir avec la technologie actuelle.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les données sur les réseau sociaux peuvent être utilisées pour créer des IA plus sophisti​quées.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La vérifcation des sources est une tâche continuellement plus difficile.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les enfants complètement protégés d''Internet ne subissent pas les effets de la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes pourraient être utilisés pour influencer les élections futures.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les IA ne peuvent jamais apprendre à mieux détecter les autres IA.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les campagnes de désinformation coordonnées utilisent des bots et des faux comptes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Une information partagée par un ami est toujours plus fiable qu''une source officielle.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les métadonnées des images contiennent des informations surl''origine et la date.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les réseaux sociaux peuvent être complètement purifiés de la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les techniques de présentation visuelle influencent la crédibilité perçue d''une info.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La diversité des perspectives aident à réduire les biais personnels.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tous les contenus en ligne sont vérifiés avant publication.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les influenceurs ont une responsabilité envers leurs followers concernant l''exactitude.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les images statiques ne peuvent jamais être générées par l''IA.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA générative peut produire du code informatique correct ou dangereux.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Le fact-checking est une activité qui demande du temps et des ressources.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les journalistes investigatifs sont inutiles à l''ère d''Internet.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes ont augmenté les cas de chantage et de harcèlement.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les documentaires et reportages n''ont jamais contenu d''erreurs.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''éducation critique des médias augmente la résistance à la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les données des utilisateurs ne sont jamais utilisées pour des deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''identité numérique peut être usurpée via des deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Le machine learning n''a aucun rapport avec la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La capacité à évaluer les sources est une compétence clé du XXIe siècle.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les jeunes sont naturellement immunisés contre la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les données biométriques peuvent être utilisées pour créer des deepfakes audio/vidéo.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Un article bien présenté peut sembler plus crédible même s''il est faux.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet est structurellement conçu pour empêcher la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les vidéos fakes constituent une menace croissante pour la confiance.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un gouvernement peut contrôler complètement la désinformation sur Internet.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La transparence concernant les contenus générés par IA est importante.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les études montrent que les rumeurs se propagent plus vite que la correction.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un million de partages garantit qu''une information est vraie.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes coûtent de moins en moins cher à produire au fil du temps.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La confiance en les institutions est affectée par la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les réseaux sociaux n''auraient jamais permis la propagation de fausses infos.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les IA discriminantes peuvent aider à détecter les deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tous les contenus visuels en ligne ont les mêmes standards d''authentification.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Le droit à la vie privée peut entrer en conflit avec la détection des deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Il est impossible d''améliorer la littératie numérique au niveau population.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les jeunes qui grandissent numérique ont aussi besoin d''éducation aux médias.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La recherche inversée d''images peut aider à vérifier l''origine d''une photo.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un texte qui semble cohérent est toujours factuel et vrai.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les images provenant des médias traditionnels sont toujours authentiques.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La photographie a aussi connu l''édition et la manipulation avant l''IA.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes vidéo demandent statistiquement moins de données qu''auparavant.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les experts dans tous les domaines comprennent les technologie automatically.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA générative ChatGPT a aidé à augmenter la productivité mais aussi la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Une même information présentation différemment est perçue différemment.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La désinformation n''affecte que les groupes vulnérables.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les enfants doivent apprendre à faire face à la désinformation dès l''école primaire.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tous les contenus générés par IA doivent obligatoirement être marqués.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les plateformes de réseaux sociaux collectent des données quis pourraient aider la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''impact psychologique de la désinformation sur jeunes est documenté.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet a rendu plus facile la vérification des informations.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les régimes autocratiques utilisent la désinformation comme outil de contrôle.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les bots sociaux n''existent que sur une plateforme.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La vérification des infos avant partage réduit la propagation dedésinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La transparence des algorithmes n''est pas importante pour les utilisateurs.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les courtés ont commence à traiter les cas de deepfakes malveillants.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La littératie numérique est une compétence passagère.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les métadonnées d''une photo peuvent révéler si elle a étémodifiée.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un article mentionnant des sources est automatiquement crédible.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les algorithmes apprennent continuellement à partir des interactions utilisateurs.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La désinformation peut avoir des conséquences physiques (violence basée sur une rumeur).', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les fact-checkers peuvent couvrir 100% de la désinformation en ligne.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les jeunes ont grandi avec Internet mais not automatiquement critique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La désinformation était absent avant l''ère numérique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La polarisation en ligne est amplifiée par les algorithmes de réseaux sociaux.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un gouvernement peut contrôler tout ce qui se passe en ligne.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les données personnelles et biométriques peuvent être utilisées malignly.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La blockchain pourrait augmenter la traçabilité et l''authenticité online.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les éducateurs n''ont pas besoin de formation en littératie numérique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Un image authentic peut être retouchée sans révéler les modifications.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les IA peuvent créer consciemment dans le but de désinformer.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''absence de sources et de références est drapeau rouge pour une info.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La confiance dans les médias peut être restaurée par plus de transparence.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un jugement humain n''est jamais affecté par algorithmes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La vérification d''informations fait partie de la responsabilité citoyenne.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet a complètement éliminé le besoin de pensée critique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Des études demontrent que le partage responsable réduisent spread fausses infos.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes peuvent avoir conséquences légales dans certaines juridictions.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La meilleure stratégie pour combattre désinformation est l''interdiction.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les algorithmes sont invisibles et non transparent pour utilisateurs.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un nombre important de partages garantit l''authenticité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les fausses infos peuvent affecter comportements de votes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet a éradiqué la nécessité de pensée critique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les images générées par IA deviennent de plus en plus difficiles à détecter.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un site web institutionnel est toujours honnête.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les IA peut être utilisée à la fois pour créer et combattre des deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les gens naïfs sont les seuls victimes de désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les données personnelles sur réseaux sociaux peuvent servir à désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La transparence complète des algorithmes est impossible.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les enfants modernes ont besoin d''éducation spécifique aux médias.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Seul les journalistes ont responsabilité pour combattre désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''impact psychologique de désinformation sur adolescents est documenté.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les technologies de détection d''IA sont 100% fiables.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La vérification des sources demande du temps et des efforts.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La polarisation politique n''a rien à voir avec désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''authenticité d''un contenu peut être vérifiée via métadonnées.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Une source ancienne et réputée peut still publier des erreurs.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les algorithmes sont programmés pour toujours dire la vérité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''aspect visuel et le design d''une info influence perception.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tout ce qui est en ligne a déjà été vérifi​é.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les vidéos fakes peuvent être créés avec data limitée.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La désinformation a disparu avec l''éducation numérique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les bots sociaux peuvent manipuler les tendances.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Seul les vieil people sont affectés par désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA peut aider experts à détecter fake images.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet rend la vérification des infos plus facile.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Une image modifiée peut sembler complètement authentique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tous les fact-checkers sont équivalents en qualité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les jeunes natifs digitaux ont toujours pensée critique.', 10is FALSE, 'Croissance digitale ne = pensée critique automatique.', FALSE),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Seuls les citoyens ignorants bois la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La transparence peut augmenter confiance dans systèmes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un lien dans une news le rend automatiquement credible.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes dev techniquement plus faciles à créer.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'La liberté d''expression means aucune responsabilité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Éduquer au scepticism est part d''cyber resilience.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''absence de source est drapeau red pour une information.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les émoticônes garantissent la sincérité d''un message. ', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les deepfakes représentent menace croissante pour identité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet rend vérification infos plus facile qu''avant.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les données personnelles peuvent être utilisées malveillants.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Pensée critique nat​urelle est difficile pour beaucoup.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les gouvernements doivent investir en éducation numérique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les réseaux sociaux éliminent complètement désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA assistance peut aider détection deepfakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Partager une Info sans vérifier est OK si populaire.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les enfants besoin de formation spécifique media.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Une vidéo trucker rédaction = garanties d''authenti​cité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA peut aussi combattre la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les experts ne sont jamais trompés par désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''accès multiple sources améliore compréhension.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Seul les pauvres éducation sont victimes désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Métadonnées images peuvent révéler éditions.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'C''est impossible d''améliorer littératie numérique.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Les IA reflètent biais dans données d''entraînement.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'La littératie médias aides jeunes naviguer info landscape.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Les IA ne peuvent jamais être utilisés against désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Sharing responsibly contributes au reducing désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet a eliminated besoin critical thinking.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Données biométriques peuvent threat to privacy.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Fact-checkers are 100% reliable always.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA peut learn from combating its own fakes.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Tous les gouvernements equally committed vérité online.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Individual actions matter in fighting désinfo.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Une video HD = guarantee d''authenticité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Réseaux sociaux responsible for some désinformation spread.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Pensée critique naturelle sans apprentissage.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Régulation IA possible sans stifling innovation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Seul les technomiens peuvent understand IA.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Désinformation affecte démocratie et confiance.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Media literacy is obsolete skill.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Combating désinfo is collective responsibility.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Internet makes source verification easier.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Deepfakes evolving faster faster techniquement.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''engagement collectif combat effectively désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Il n''existe aucune solution pour la désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Media literacy enhances democratic participation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Expert opinions ne peuvent jamais nécessiter vérification.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'L''IA peut amplifier ou reduire biais.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'L''authenticité visuelle garanties contenu vérité.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Societal solutions require multisectoral collaboration.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Pensée critique naturellement developed sans éducation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Individual contributions matter in information ecosystem.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Technology solves completely désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Éducation best investment against misinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Everyone equally vulnerable to désinformation tactics.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Régulation balance freedom with protection.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Un problème simplement resolved techniquement.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Societal trust damaged by pervasive désinformation.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Younger generation immune to fake information.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Digital citizenship requires ethical responsibility.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, FALSE, 'Government exclusively responsible for combating désinfo.', 10),
(2, NULL, 'Vrai', 'Faux', NULL, NULL, TRUE, 'Transparency increases system trustworthiness.', 10);
