version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: specialweek-backend
    ports:
      - "8080:8080"

  db:
    image: mysql:8.4
    container_name: specialweek-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: specialweek
      MYSQL_USER: specialweek
      MYSQL_PASSWORD: specialweek
    ports:
      - "3306:3306"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: specialweek-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - db

